### ISSUE TITLE
Full Name and Open button doesn't show up if name is longer 

### ISSUE THREAD

**Issue by akshayjk** [PredixDev/px-context-browser#20]
Hi Team,

We are facing an issue, when the name of member in the list is longer, scroll bar comes up, but if we scroll, remaining name and 'open' button disappears. I am attaching the screenshots for the same.
1. Scroll Bar to extreme left
   ![px-browser-1](https://cloud.githubusercontent.com/assets/6094325/18863854/3309076c-84b1-11e6-867b-6544c323d624.PNG)
2. Scroll Bar to Extreme right
   ![px-browser-2](https://cloud.githubusercontent.com/assets/6094325/18863855/3507c396-84b1-11e6-8cd3-f57dcbfa2c82.PNG)

**Comment by randyaskin** [comment]
It looks like this might have been caused by your implementation - I would guess the white space shown in your second screenshot covering up the Open button is equal to the space you introduced to the left side of the panel for the icon. That being said, our team already changed context-browser to support line-break for very long words. Since your item name doesn't seem to have any white space in it, you'd also need to add `word-break: break-word` or `word-break: break-all` as well. Please try in your local and, if it works, consider submitting a pull request with the fix.
