### ISSUE TITLE
Problem in setting up the json

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-context-browser#24]
# Submit an Issue

Hi,

I have browser context called on my html, however it was not pulling the json from the folder(px-context-browser). I've also tried calling initialContext and directContext json through iron-ajax in the html still it didn't populate the json. Can please suggest how to set this up?

<iron-ajax url="../px-context-browser/intialContext.json" last-response="{{browserContext}}" auto></iron-ajax> - i've called like this, also clarify what is this last-response does?

Do we need to include below 2 dependency as well?
    "px-tabs": "^0.6.0",
    "px-api-viewer": "^0.1.0",

**Comment by runn-vermel** [comment]
HI @anundinesh 

It seems you have several issues you're dealing with, i'll try to answer them all:

1. example of connecting the json can be found here: https://github.com/PredixDev/px-context-browser/blob/ece4739e26820c7d2ef5176768509e4b4aa0d214/demo.html
2. last-response is iron-ajax's way of data binding the response it gets into a data bounded variable that can then be referenced anywhere within the template using is="dom-bind". You can read more about at the iron-ajax documentation: https://elements.polymer-project.org/elements/iron-ajax
3. the two bower entries you have up there are under the DEVdependencies section. this means you do NOT need them for production. we use them in our demo page. Here's a good stackOverflow answer to the difference between the two. http://stackoverflow.com/questions/19339227/bower-and-devdependencies-vs-dependencies

I'm going to close this, since this isn't an issue, so much as a question of how to. please feel free to re-open this if you find an issue.
