### ISSUE TITLE
Context Browser is not rendering properly in IE11.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-context-browser#56]
## Expected behavior and actual behavior:

Getting an 'undefined promise' in the dist version of context browser in IE11. Nothing other than the filter is rendered. 

## Environment:
CB: Redesign branch
Browser: IE11 on win7

### IE11:

![2017-07-10_1145](https://user-images.githubusercontent.com/10835611/28034461-18547014-6566-11e7-9868-b724d1deb0e9.png)

### Firefox:

![screen shot 2017-07-10 at 11 50 28 am](https://user-images.githubusercontent.com/10835611/28034491-273f8bc2-6566-11e7-92a5-36df83fd25f7.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
This specific issue was fixed in px-app-helpers (https://github.com/PredixDev/px-app-helpers/commit/a598e19e377c2a5e88016fdc2d209fddeaa0bc55) by adding some additional Symbol polyfills. There are still other issues with rendering in IE11 but those are represented on different issue threads. Closing this one since this piece is fixed.
