### ISSUE TITLE
Component fails in IE 11 and Edge

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-context-browser#81]
## Expected behavior and actual behavior:
Component should function in MS browsers, like it does in all the other grown up browsers.

## Steps to reproduce the problem:
Open the page in IE 11 or MS Edge:
https://www.predix-ui.com/#/elements/context-browser/px-context-browser
Component fails to load on the page.  Errors appear in the console.  
These may be errors running ES6 constructs such as "const".
Also showing errors in the console loading GEInspiraSans font in IE 11.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Windows 10.  Both IE 11 and Edge 25.

**Comment by davidrleonard** [comment]
@gstroup Thanks for the bug report.

As we upgrade and refactor components, we're introducing ES6 style JavaScript (like `const` which is throwing the error here). We'll slowly be moving more components over to use ES6 features, especially as we look toward Polymer 2/3, which use the `class X extends Polymer.Element` syntax rather than the `Polymer({ is: 'X' })` factory syntax for defining custom elements.

To use the context browser and other components in IE11, we recommend our customers transpile their code when they build it for production. The [polymer cli's build pipeline](https://www.polymer-project.org/2.0/toolbox/build-for-production) tool is a good choice for doing this and also supports on-the-fly transpilation during development using the `polymer serve` command. For projects already using webpack or some other build system, there is likely a hook for transpiling code already in their build process, or one should be easy to implement.

I have an open to-do on our demo site to figure out how we'll handle this for our demos. I expect we'll either do transpilation there, or recommend people viewing the site in IE11 use an alternate browser (transpilation adds overhead, and we only receive >3-5% of our traffic from IE11).
